
###Lista de productos
GET http://localhost:3000/productos

###consulta por id de producto
GET http://localhost:3000/productos/20

### agregar un nuevo producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  
  "precio": 2000,
  "descripcion": "Zapatillas para correr de alta calidad.",
  "disponible": true
}

### Actualziar un producto
PUT http://localhost:3000/productos/20
Content-Type: application/json

{
    "nombre": "Zapatillas casuales",
    "precio": 1320,
    "descripcion": "Zapatillas",
    "disponible": true
}


### eliminar producto por id
DELETE  http://localhost:3000/productos/20